# Use this, if your inverter won't enter standby mode, even if the battery is completely discharged, 
# the sun is down and you don't have backup power enabled
# This "feature" was implemented by a firmware update in January 2025. 
# If several conditions are met, the inverter is put into "shutdown" mode and re-enabled after 1 minute

alias: Sungrow_Go_to_Standby_quirk
description: ""
triggers:
  - trigger: time_pattern
    minutes: /10
conditions:
  - condition: state
    entity_id: sensor.sungrow_inverter_state
    state: Running
    for:
      hours: 1
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: binary_sensor.battery_discharging_delay
    state: "off"
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - condition: state
    entity_id: binary_sensor.pv_generating_delay
    state: "off"
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - condition: numeric_state
    entity_id: sensor.mppt1_voltage
    below: 10
  - condition: numeric_state
    entity_id: sensor.mppt2_voltage
    below: 10
  - condition: state
    entity_id: sensor.ems_mode_selection
    state: Self-consumption mode (default)
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: sensor.backup_mode
    state: Disabled
actions:
  - action: input_select.select_option
    metadata: {}
    data:
      option: Shutdown
    target:
      entity_id: input_select.set_sg_inverter_run_mode
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
  - action: input_select.select_option
    metadata: {}
    data:
      option: Enabled
    target:
      entity_id: input_select.set_sg_inverter_run_mode
mode: single
